name : Update IPL analytics

permissions:
  contents: write # permission for GitHub Actions to push commits back to the repo

on: # specifies when the workflow should be triggered (2 trigegrs: workflow_dispatch and schedule)
  workflow_dispatch: #manual trigger via github UI
  schedule: #define schedule for automatic trigger.Based on cron expression
    - cron: "30 4 * 4,5 *"  #cron -> schedule for repeating task based on time
                          # "min hour day_of_month month day_of_week"
                          #run everyday at 4:30AM everyday in April,May
jobs: #jobs to be executed in the workflow (set of steps executed in a runner/container)
  update: #name of the job
    runs-on: ubuntu-latest #run of latest version of Ubuntu runner (vm with Ubunut installed) 

    steps: 
      - name: Check out repository 
        uses: actions/checkout@v4 #uses the checkout action in Github which downloads the repo into the vm

      - name: Set up Python 
        uses: actions/setup-python@v6 #uses the setup python action to set up python in the runner
        with:
          python-version: "3.11" #pass the parameter i.e. Python version to the action
        
      - name: Install dependencies
        run: | #run the following shell commands. Pipe | allows to specify multi line commands
          python -m pip install --upgrade pip
          pip install pandas tabulate

      # Download the latest JSON files & extract it and overwrite the old ones
      - name : Download latest IPL JSON data
        run: |
          # curl : transfers data to/from a server.
          # -L : curl will automatically follow the redirects until it reaches the final destination.
          curl -L "<>" -o data/raw/ipl_json.zip
          unzip -o data/raw/ipl_json.zip -d data/raw/cricksheet_ipl_json #-o: overwrite, -d: destination for extraction
      
      # run the python scripts
      - name: Run build matches script
        run: python src/build_matches_table.py
      
      - name: Run analytics script
        run: python src/analyze_matches.py
      
      # commit & push the changes
      - name: Commit and push updated outputs
        run: |
          # set identity of git using GitHub bot in the container
          # https://github.com/marketplace/actions/bot-details
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          
          git add data/processed output
          git diff --cached --quiet || git commit -m "Update IPL analytics outputs after a game" #only commit if there has been changes
          git push


